#!/bin/bash

echo "[compiling]"
gcc -Wimplicit-function-declaration -Wformat-truncation=0 -Wint-conversion -c src/bbuffer.c src/mtwwwd.c src/sem.c -g

if [ ! -d ./bin ]; then
    mkdir bin
fi

mv *.o ./bin

echo "[linking]"
gcc -pthread ./bin/*.o -o mtwwwd

echo "[running]"
./mtwwwd "$@" 